// Generated by shadcn (base-nova), edited for spec 0003: token colours, the preset focus
// rings removed (one global :focus-visible rule), sizes sm/default/icon at 32/36 px, a solid
// destructive fill, and a `loading` state that keeps focus and width (AC-5).
"use client";

import { Button as ButtonPrimitive } from "@base-ui/react/button";
import { cva, type VariantProps } from "class-variance-authority";
import type * as React from "react";

import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "group/button relative inline-flex shrink-0 items-center justify-center gap-1.5 rounded-md border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-colors select-none disabled:pointer-events-none disabled:opacity-50 aria-busy:cursor-progress [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        outline: "border-input bg-transparent hover:bg-accent hover:text-accent-foreground",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
      },
      size: {
        sm: "h-8 px-3",
        default: "h-9 px-4",
        icon: "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

type ButtonBaseProps = Omit<ButtonPrimitive.Props, "aria-label"> &
  Omit<VariantProps<typeof buttonVariants>, "size"> & {
    /** Busy: ignores clicks, keeps focus, and shows a spinner over the label. */
    loading?: boolean;
  };

/** An icon button has no visible text, so its accessible name is required. */
type ButtonProps =
  | (ButtonBaseProps & { size?: "sm" | "default"; "aria-label"?: string })
  | (ButtonBaseProps & { size: "icon"; "aria-label": string });

function Button({
  className,
  variant = "default",
  size = "default",
  loading = false,
  onClick,
  children,
  ...props
}: ButtonProps) {
  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    if (loading) {
      event.preventDefault();
      return;
    }
    // Base UI's click handler type carries its own event details; a plain call is enough here.
    (onClick as ((e: React.MouseEvent<HTMLButtonElement>) => void) | undefined)?.(event);
  };

  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size }), className)}
      aria-disabled={loading || undefined}
      aria-busy={loading || undefined}
      onClick={handleClick}
      {...props}
    >
      {loading ? (
        <>
          <span className="invisible inline-flex items-center gap-1.5">{children}</span>
          <span className="absolute inset-0 flex items-center justify-center" aria-hidden="true">
            <Spinner />
          </span>
        </>
      ) : (
        children
      )}
    </ButtonPrimitive>
  );
}

export { Button, buttonVariants, type ButtonProps };
