// Generated by shadcn (base-nova), edited for spec 0003: decorative by default (aria-hidden,
// no role), because text beside it always carries the meaning (AC-9, AC-13).
import { Loader2Icon } from "lucide-react";
import type * as React from "react";

import { cn } from "@/lib/utils";

function Spinner({ className, ...props }: React.ComponentProps<"svg">) {
  return (
    <Loader2Icon
      data-slot="spinner"
      aria-hidden="true"
      className={cn("size-4 animate-spin", className)}
      {...props}
    />
  );
}

export { Spinner };
