// Typed client for the Swing Scan API (spec 0002). `schema.d.ts` is generated by
// `make gen-client` from contracts/openapi.json; this wrapper is the only hand written file.
import createFetchClient, { type ClientOptions } from "openapi-fetch";

import type { components, paths } from "./schema";

export type { components, paths } from "./schema";

/** Every component schema by name, e.g. `Schemas["ScanResponse"]`. */
export type Schemas = components["schemas"];

export type ScanRequest = Schemas["ScanRequest"];
export type ScanResponse = Schemas["ScanResponse"];
export type BacktestRequest = Schemas["BacktestRequest"];
export type BacktestResponse = Schemas["PortfolioResult"] | Schemas["TradeLabResult"];
export type Rule = Schemas["Rule"];
export type ExitConfig = Schemas["ExitConfig"];
export type IndicatorSpec = Schemas["IndicatorSpec"];
export type TemplateOut = Schemas["TemplateOut"];
export type MetaResponse = Schemas["MetaResponse"];

export type ApiClient = ReturnType<typeof createFetchClient<paths>>;

/** An openapi-fetch client bound to the API paths. `baseUrl` is the API origin. */
export function createClient(options: ClientOptions = {}): ApiClient {
  return createFetchClient<paths>(options);
}
