/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backtest
         * @description 1 config runs a portfolio backtest; 2 to 6 configs run the exit lab (trade mode).
         */
        post: operations["backtest_api_v1_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness check for the Lambda Web Adapter and the web app's warm up ping.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicators
         * @description Every indicator with its `n` bounds, from the same registry that validates rules.
         */
        get: operations["indicators_api_v1_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description The contract version, plus the dataset once scope feature 7 loads one.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Tickers whose rule is true on `as_of` (S-1).
         */
        post: operations["scan_api_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Templates
         * @description The two built in rule templates (doc 02 §5.2).
         */
        get: operations["templates_api_v1_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Assumptions
         * @description Every setting that shaped the result, echoed so a run can be reproduced.
         */
        Assumptions: {
            /** Baseline Config Index */
            baseline_config_index: number;
            /** Commission Bps */
            commission_bps: number;
            /** Configs */
            configs: components["schemas"]["ExitConfig"][];
            /** Cooldown Bars */
            cooldown_bars: number;
            /**
             * Cooldown Basis
             * @constant
             */
            cooldown_basis: "signal";
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "synthetic" | "live";
            /** Data Seed */
            data_seed: number | null;
            /** Data Version */
            data_version: string;
            /**
             * Delisting Rule
             * @constant
             */
            delisting_rule: "exit_last_close";
            /**
             * Entry Rising Edge
             * @constant
             */
            entry_rising_edge: true;
            /**
             * Fill Model
             * @constant
             */
            fill_model: "signal_close_entry_next_open";
            /** Horizon Bars */
            horizon_bars: number | null;
            /** Max Positions */
            max_positions: number | null;
            /**
             * No Last Bar Entry
             * @constant
             */
            no_last_bar_entry: true;
            /** Oos Fraction */
            oos_fraction: number;
            /**
             * Oos Start
             * Format: date
             */
            oos_start: string;
            /** Same Ticker Overlap */
            same_ticker_overlap: boolean;
            /** Seed */
            seed: number | null;
            /**
             * Sizing
             * @enum {string}
             */
            sizing: "equal_weight" | "unit_notional";
            /** Slippage Bps */
            slippage_bps: number;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /** Configs */
            configs: components["schemas"]["ExitConfig"][];
            rule: components["schemas"]["Rule"];
            sim?: components["schemas"]["SimParams"];
        };
        /** BenchmarkMetrics */
        BenchmarkMetrics: {
            /** Cagr Pct */
            cagr_pct: number | null;
            /** Max Dd Pct */
            max_dd_pct: number | null;
        };
        /** BenchmarkSplit */
        BenchmarkSplit: {
            is: components["schemas"]["BenchmarkMetrics"];
            oos: components["schemas"]["BenchmarkMetrics"];
        };
        /**
         * BestIs
         * @description The config index with the best IS value per ranked metric. OOS is never ranked (X-3).
         */
        BestIs: {
            /** Avg Loss Pct */
            avg_loss_pct: number | null;
            /** Avg Mae Pct */
            avg_mae_pct: number | null;
            /** Avg Mfe Pct */
            avg_mfe_pct: number | null;
            /** Avg Win Pct */
            avg_win_pct: number | null;
            /** Expectancy Pct */
            expectancy_pct: number | null;
            /** Expectancy Per Bar Pct */
            expectancy_per_bar_pct: number | null;
            /** Expectancy R */
            expectancy_r: number | null;
            /** Horizon Exit Pct */
            horizon_exit_pct: number | null;
            /** Profit Factor */
            profit_factor: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
        };
        /**
         * CloseBelowMa
         * @description Exit at the next open after a close below the moving average.
         */
        CloseBelowMa: {
            /**
             * Ma
             * @default sma
             * @enum {string}
             */
            ma: "sma" | "ema";
            /**
             * N
             * @default 21
             */
            n: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "close_below_ma";
        };
        /** Condition */
        Condition: {
            left: components["schemas"]["IndOperand"];
            /**
             * Op
             * @enum {string}
             */
            op: ">" | "<" | ">=" | "<=" | "crosses_above" | "crosses_below";
            /** Right */
            right: components["schemas"]["IndOperand"] | components["schemas"]["ValueOperand"];
        };
        /** ConfigRow */
        ConfigRow: {
            edge: components["schemas"]["EdgeSplit"];
            /** Name */
            name: string;
            random: components["schemas"]["TradeSplit"];
            strategy: components["schemas"]["TradeSplit"];
        };
        /**
         * DataMeta
         * @description `meta.json`: describes one dataset. `benchmark` is excluded from every universe.
         */
        DataMeta: {
            /** Benchmark */
            benchmark: string;
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "synthetic" | "live";
            /** Data Version */
            data_version: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** N Tickers */
            n_tickers: number;
            /** Seed */
            seed: number | null;
            /**
             * Start
             * Format: date
             */
            start: string;
            /** Survivors Only */
            survivors_only: boolean;
        };
        /**
         * EdgeMetrics
         * @description Strategy minus random, per metric. Null when either side is null.
         */
        EdgeMetrics: {
            /** Expectancy Pct */
            expectancy_pct: number | null;
            /** Expectancy Per Bar Pct */
            expectancy_per_bar_pct: number | null;
            /** Expectancy R */
            expectancy_r: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
        };
        /** EdgeSplit */
        EdgeSplit: {
            is: components["schemas"]["EdgeMetrics"];
            oos: components["schemas"]["EdgeMetrics"];
        };
        /** Entries */
        Entries: {
            /** Count */
            count: number;
            /** Distinct Weeks */
            distinct_weeks: number;
            /** Hash */
            hash: string;
            /** Is Count */
            is_count: number;
            /** Oos Count */
            oos_count: number;
            /** Random Is Count */
            random_is_count: number;
            /** Random Oos Count */
            random_oos_count: number;
        };
        /**
         * ExitConfig
         * @description A named set of 1 to 6 exits, each of a distinct type.
         */
        ExitConfig: {
            /** Exits */
            exits: (components["schemas"]["StopPct"] | components["schemas"]["StopAtr"] | components["schemas"]["Target"] | components["schemas"]["TrailPct"] | components["schemas"]["CloseBelowMa"] | components["schemas"]["TimeExit"])[];
            /** Name */
            name: string;
        };
        /**
         * Guides
         * @description Stop and target guides from the baseline config's IS trades only (X-5).
         */
        Guides: {
            /** Mfe Median Pct */
            mfe_median_pct: number | null;
            /** Winner Mae P75 Pct */
            winner_mae_p75_pct: number | null;
            /** Winner Mae P90 Pct */
            winner_mae_p90_pct: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndOperand
         * @description An indicator value, optionally shifted back `offset` bars and scaled by `mult`.
         */
        IndOperand: {
            /**
             * Ind
             * @enum {string}
             */
            ind: "open" | "high" | "low" | "close" | "volume" | "sma" | "ema" | "rsi" | "atr" | "highest" | "lowest" | "avg_volume" | "ret" | "rs";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ind";
            /**
             * Mult
             * @default 1
             */
            mult: number;
            /** N */
            n?: number | null;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /**
         * IndicatorSpec
         * @description One registry row. Non windowed indicators (price fields) take no `n`.
         */
        IndicatorSpec: {
            /** Label */
            label: string;
            /** N Default */
            n_default: number | null;
            /** N Max */
            n_max: number | null;
            /** N Min */
            n_min: number | null;
            /**
             * Name
             * @enum {string}
             */
            name: "open" | "high" | "low" | "close" | "volume" | "sma" | "ema" | "rsi" | "atr" | "highest" | "lowest" | "avg_volume" | "ret" | "rs";
            /** Windowed */
            windowed: boolean;
        };
        /** MetaResponse */
        MetaResponse: {
            /** Contract Version */
            contract_version: string;
            data: components["schemas"]["DataMeta"] | null;
            /** Oos Start */
            oos_start: string | null;
        };
        /**
         * NotImplementedBody
         * @description The 501 body while a use case's scope feature has not landed.
         */
        NotImplementedBody: {
            /** Detail */
            detail: string;
        };
        /** Point */
        Point: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
        /** PortfolioMetrics */
        PortfolioMetrics: {
            /** Avg Bars Held */
            avg_bars_held: number | null;
            /** Avg Loss Pct */
            avg_loss_pct: number | null;
            /** Avg Win Pct */
            avg_win_pct: number | null;
            /** Cagr Pct */
            cagr_pct: number | null;
            /** Expectancy Pct */
            expectancy_pct: number | null;
            /** Expectancy R */
            expectancy_r: number | null;
            /** Exposure Pct */
            exposure_pct: number | null;
            /** Max Dd Pct */
            max_dd_pct: number | null;
            /** N Trades */
            n_trades: number;
            /** Profit Factor */
            profit_factor: number | null;
            /** Sharpe */
            sharpe: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
        };
        /** PortfolioResult */
        PortfolioResult: {
            assumptions: components["schemas"]["Assumptions"];
            /** Benchmark */
            benchmark: components["schemas"]["Point"][];
            benchmark_metrics: components["schemas"]["BenchmarkSplit"];
            /** Equity */
            equity: components["schemas"]["Point"][];
            metrics: components["schemas"]["PortfolioSplit"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "portfolio";
            /**
             * Oos Start
             * Format: date
             */
            oos_start: string;
            /** Trades */
            trades: components["schemas"]["Trade"][];
            /** Trades Total */
            trades_total: number;
            /** Trades Truncated */
            trades_truncated: boolean;
            trial: components["schemas"]["Trial"];
            /** Warnings */
            warnings: components["schemas"]["Warning"][];
        };
        /** PortfolioSplit */
        PortfolioSplit: {
            is: components["schemas"]["PortfolioMetrics"];
            oos: components["schemas"]["PortfolioMetrics"];
        };
        /**
         * Rule
         * @description An entry rule: 1 to 8 conditions joined by AND. No hidden price filter (ADR-013).
         */
        Rule: {
            /** Conditions */
            conditions: components["schemas"]["Condition"][];
            /** Name */
            name: string;
        };
        /** ScanRequest */
        ScanRequest: {
            /** As Of */
            as_of?: string | null;
            rule: components["schemas"]["Rule"];
        };
        /** ScanResponse */
        ScanResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Columns */
            columns: string[];
            /** Rows */
            rows: components["schemas"]["ScanRow"][];
        };
        /** ScanRow */
        ScanRow: {
            /** Chg Pct */
            chg_pct: number | null;
            /** Close */
            close: number;
            /** New Today */
            new_today: boolean;
            /** Operands */
            operands: number[];
            /** Ticker */
            ticker: string;
            /** Vol Ratio */
            vol_ratio: number | null;
        };
        /** SimParams */
        SimParams: {
            /** End */
            end?: string | null;
            /**
             * Horizon Bars
             * @default 60
             */
            horizon_bars: number;
            /**
             * Max Positions
             * @default 10
             */
            max_positions: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
            /**
             * Slippage Bps
             * @default 10
             */
            slippage_bps: number;
            /** Start */
            start?: string | null;
        };
        /**
         * StopAtr
         * @description Stop loss `k` ATRs (of length `n`) below the entry fill.
         */
        StopAtr: {
            /**
             * K
             * @default 2
             */
            k: number;
            /**
             * N
             * @default 14
             */
            n: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stop_atr";
        };
        /**
         * StopPct
         * @description Stop loss a fixed percent below the entry fill.
         */
        StopPct: {
            /**
             * Pct
             * @default 8
             */
            pct: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stop_pct";
        };
        /**
         * Target
         * @description Profit target a fixed percent above the entry fill.
         */
        Target: {
            /**
             * Pct
             * @default 15
             */
            pct: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "target";
        };
        /** TemplateOut */
        TemplateOut: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            rule: components["schemas"]["Rule"];
        };
        /**
         * TimeExit
         * @description Exit after a fixed number of bars held.
         */
        TimeExit: {
            /**
             * Bars
             * @default 10
             */
            bars: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "time";
        };
        /** Trade */
        Trade: {
            /** Bars Held */
            bars_held: number;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            /** Entry Price */
            entry_price: number;
            /**
             * Exit Date
             * Format: date
             */
            exit_date: string;
            /** Exit Price */
            exit_price: number;
            /**
             * Exit Reason
             * @enum {string}
             */
            exit_reason: "stop_pct" | "stop_atr" | "trail_pct" | "target" | "time" | "ma" | "delisted" | "horizon" | "end_of_test";
            /** Mae Pct */
            mae_pct: number;
            /** Mae R */
            mae_r: number | null;
            /** Mfe Pct */
            mfe_pct: number;
            /** Mfe R */
            mfe_r: number | null;
            /** R Multiple */
            r_multiple: number | null;
            /** Return Pct */
            return_pct: number;
            /**
             * Segment
             * @enum {string}
             */
            segment: "is" | "oos";
            /** Ticker */
            ticker: string;
        };
        /** TradeLabResult */
        TradeLabResult: {
            assumptions: components["schemas"]["Assumptions"];
            /** Baseline Trades */
            baseline_trades: components["schemas"]["Trade"][];
            /** Baseline Trades Total */
            baseline_trades_total: number;
            /** Baseline Trades Truncated */
            baseline_trades_truncated: boolean;
            best_is: components["schemas"]["BestIs"];
            entries: components["schemas"]["Entries"];
            guides_is: components["schemas"]["Guides"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "trade";
            /**
             * Oos Start
             * Format: date
             */
            oos_start: string;
            /** Rows */
            rows: components["schemas"]["ConfigRow"][];
            trial: components["schemas"]["Trial"];
            /** Warnings */
            warnings: components["schemas"]["Warning"][];
        };
        /**
         * TradeMetrics
         * @description Per trade metrics. No CAGR, max DD or Sharpe in trade mode (X-8).
         */
        TradeMetrics: {
            /** Avg Bars Held */
            avg_bars_held: number | null;
            /** Avg Loss Pct */
            avg_loss_pct: number | null;
            /** Avg Mae Pct */
            avg_mae_pct: number | null;
            /** Avg Mfe Pct */
            avg_mfe_pct: number | null;
            /** Avg Win Pct */
            avg_win_pct: number | null;
            /** Distinct Weeks */
            distinct_weeks: number;
            /** Expectancy Pct */
            expectancy_pct: number | null;
            /** Expectancy Per Bar Pct */
            expectancy_per_bar_pct: number | null;
            /** Expectancy R */
            expectancy_r: number | null;
            /** Horizon Exit Pct */
            horizon_exit_pct: number | null;
            /** N Trades */
            n_trades: number;
            /** Profit Factor */
            profit_factor: number | null;
            /** Win Rate Pct */
            win_rate_pct: number | null;
        };
        /** TradeSplit */
        TradeSplit: {
            is: components["schemas"]["TradeMetrics"];
            oos: components["schemas"]["TradeMetrics"];
        };
        /**
         * TrailPct
         * @description Trailing stop a fixed percent below the highest high since entry.
         */
        TrailPct: {
            /**
             * Pct
             * @default 10
             */
            pct: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "trail_pct";
        };
        /** Trial */
        Trial: {
            /** Pair Keys */
            pair_keys: string[];
            /** Structure Key */
            structure_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValueOperand
         * @description A fixed number, such as the 5 in `close > 5`.
         */
        ValueOperand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "value";
            /** Value */
            value: number;
        };
        /** Warning */
        Warning: {
            /**
             * Code
             * @enum {string}
             */
            code: "no_entries" | "horizon_exits_over_10pct" | "trades_truncated";
            /** Config Index */
            config_index: number | null;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtest_api_v1_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResult"] | components["schemas"]["TradeLabResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedBody"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    indicators_api_v1_indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorSpec"][];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    scan_api_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not implemented yet */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotImplementedBody"];
                };
            };
        };
    };
    templates_api_v1_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
        };
    };
}
